### ISSUE TITLE
PEP8Bear `Line affected` error?

### ISSUE THREAD

**Issue by JudiciaryPag** [coala/coala-bears#1945] opened 2017-07-24 09:52 UTC
Most of my `Line affected` values are too low. Sadly my code is not open-source so I am unable to share it but this should be easily reproduced because it happens in every file. The code it echos for `Line affected` is actually several lines higher in the file, i.e. an affected line of `37` is actually line `40` in the file.

Also there are warnings for consecutive lines, yet they're all reported as `Line affected 37`.

I'm using the latest release `coala-bears 0.12.0.dev20170724060442`

**Comment by Makman2** [comment] 2017-07-24 15:21
If your code is not open-source, could you try to construct an example where it occurs for you? Especially a coafile would be nice (if possible a minimum working example).

**Comment by JudiciaryPag** [comment] 2017-07-24 16:06
Here's a fragment of a file that exhibits the fault, and the (simple) coafile (both as `txt` files to allow attachment).

When I run `coala` I am told...

```
[----] /Users/alan/Code/MatildaPeak/patterneer/db_inspect.py
[++++] /Users/alan/Code/MatildaPeak/patterneer/db_inspect.py
[    ] Line affected 46
[    ] 
[----] accumulators = session.query(Accumulator).filter(Accumulator.pattern == pattern).all()
[    ] Line affected 46
[    ] 
[----] monostables = session.query(Monostable).filter(Monostable.pattern == pattern).all()
[++++] accumulators = session.query(Accumulator).filter(
[++++]     Accumulator.pattern == pattern).all()
[++++] monostables = session.query(Monostable).filter(
[++++]     Monostable.pattern == pattern).all()
[    ] Displayed patch successfully.
```

Yet, as you will see, the offending lines are `49` and `51`.

[coafile.txt](https://github.com/coala/coala-bears/files/1170403/coafile.txt)
[db_inspect.py.txt](https://github.com/coala/coala-bears/files/1170404/db_inspect.py.txt)

**Comment by Makman2** [comment] 2017-07-24 16:36
Confirmed. Again there appears to be a shift of 3 lines.

**Comment by Makman2** [comment] 2017-07-24 16:37
CC @Nosferatul

**Comment by EverWinter23** [comment] 2018-01-26 10:30
db_inspect.py
|  49| accumulators·=·session.query(Accumulator).filter(Accumulator.pattern·==·pattern).all()
|  50| monostables·=·session.query(Monostable).filter(Monostable.pattern·==·pattern).all()
|    | [NORMAL] PEP8Bear:
|    | The code does not comply to PEP8.
|    | +4 -2 in /home/frost/in/db_inspect.py
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Apply patch
|    |  3: Show patch
|    |  4: Add ignore comment
|    | Enter number (Ctrl-D to exit): 
(coal) frost@winter:~/in$ 

No shift of 3 lines.

**Comment by JudiciaryPag** [comment] 2018-01-26 13:26
Excellent. At the moment I'm using `0.12.0.dev20171110210444`

**Comment by Makman2** [comment] 2018-01-26 16:45
Probably an update from `pylint`'s side? It's been a while since we have stopped releasing development-versions on pypi.

**Comment by Makman2** [comment] 2018-01-26 16:45
In that case we should increase the minimum version of `pylint` :+1:

**Comment by EverWinter23** [comment] 2018-01-26 19:36
Since this is the output of the pep8 Bear which does not use pylint, I think the underlying issue is something else.

**Comment by Makman2** [comment] 2018-01-27 16:01
Oops my bad, I've misread the title. Yes then something in PEP8 may have changed :+1:

**Comment by Naveenaidu** [comment] 2018-02-14 17:09
Hello,If the issue is still open, I would like to be assigned to this issue.

**Comment by Naveenaidu** [comment] 2018-02-15 14:21
db_inspect.py
| 49| accumulators·=·session.query(Accumulator).filter(Accumulator.pattern·==·pattern).all()
| 50| monostables·=·session.query(Monostable).filter(Monostable.pattern·==·pattern).all()
| | [NORMAL] PEP8Bear:
| | The code does not comply to PEP8.
| | +4 -2 in /home/frost/in/db_inspect.py
| | *0: Do nothing
| | 1: Open file(s)
| | 2: Apply patch
| | 3: Show patch
| | 4: Add ignore comment
| | Enter number (Ctrl-D to exit):

No shift of 3 lines. It is working as expected. Can you check it out. I think this issue needs to be closed.

**Closed** 2018-02-15 15:39 UTC
Labels: difficulty/low, importance/high, type/bug
