### ISSUE TITLE
Bear Proposal: Add Eastwood for Clojure

### ISSUE THREAD

**Issue by vijeth-aradhya** [coala/coala-bears#1596] opened 2017-04-09 06:24 UTC
Well, there is [kibit](https://github.com/jonase/kibit) for linting Clojure files as well. But, I think [Eastwood](https://github.com/jonase/eastwood) does a slightly better job.

**Comment by sangamcse** [comment] 2018-02-22 19:52
Duplicate of https://github.com/coala/coala-bears/issues/151
cc @Makman2

**Closed** 2018-02-22 20:21 UTC
Labels: status/duplicate
