### ISSUE TITLE
Update Rubocop to 0.51.0 

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#2117] opened 2017-11-09 11:18 UTC
Required to support `haml-lint` `0.27.0` for https://github.com/coala/coala-bears/pull/1914
Opened by @IpshitaC at [Gitter](https://gitter.im/coala/coala?at=5a04399ad6c36fca31f5f101)

**Comment by jayvdb** [comment] 2017-11-09 11:22
I think this is a duplicate of https://github.com/coala/coala-bears/issues/2116 ?

**Comment by IpshitaC** [comment] 2017-11-09 11:26
@jayvdb Oh alright! Should I then just raise a PR with [these changes](https://github.com/coala/coala-bears/pull/1914/commits/bfb8c2fc3d06da19653c029ed22207d70b8b05ea), referencing https://github.com/coala/coala-bears/issues/2116 only?

**Comment by jayvdb** [comment] 2017-11-09 11:30
Just the `rubocop` version change, referencing #2116.  Thanks.

**Comment by IpshitaC** [comment] 2017-11-09 11:31
Sure! :+1:  I'll just raise the PR. Should I close this issue then?

**Comment by userzimmermann** [comment] 2017-11-10 12:22
@jayvdb @RaiVaibhav @IpshitaC Can you please help me see the actual connection to #2116 ? :)

**Comment by RaiVaibhav** [comment] 2017-11-10 15:14
Close this issue, Now need of this issue

**Comment by userzimmermann** [comment] 2017-11-10 15:19
@RaiVaibhav Thanks for explaining :)

So I'm closing this issue since it was solved by https://github.com/coala/coala-bears/pull/2118

**Closed by userzimmermann** 2017-11-10 15:19 UTC
