### ISSUE TITLE
chktexbear fails to run

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#317] opened 2016-04-05 22:05 UTC
Running `py.test -k Latex` on archlinux with chktex v1.7.4 yields:

```
E           Bear LatexLintBear failed to run. Take a look at debug messages for further information.
E           The bear LatexLintBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.
E           
E           Traceback information is provided below:
E           
E           Traceback (most recent call last):
E             File "/usr/lib/python3.5/site-packages/coala-0.6.0.dev99999999999999-py3.5.egg/coalib/bears/Bear.py", line 97, in execute
E               return list(self.run_bear_from_section(args, kwargs) or [])
E             File "/usr/lib/python3.5/site-packages/coala-0.6.0.dev99999999999999-py3.5.egg/coalib/bears/Bear.py", line 90, in run_bear_from_section
E               return self.run(*args, **kwargs)
E             File "/home/lasse/prog/coala-bears/bears/latex/LatexLintBear.py", line 21, in run
E               return self.lint(filename)
E             File "/usr/lib/python3.5/site-packages/coala-0.6.0.dev99999999999999-py3.5.egg/coalib/bearlib/abstractions/Lint.py", line 96, in lint
E               stdin=stdin_input)
E             File "/usr/lib/python3.5/site-packages/coala-0.6.0.dev99999999999999-py3.5.egg/coalib/misc/Shell.py", line 56, in run_shell_command
E               ret = p.communicate(stdin)
E             File "/usr/lib/python3.5/subprocess.py", line 1068, in communicate
E               stdout, stderr = self._communicate(input, endtime, timeout)
E             File "/usr/lib/python3.5/subprocess.py", line 1741, in _communicate
E               self.stdout.encoding)
E             File "/usr/lib/python3.5/subprocess.py", line 979, in _translate_newlines
E               data = data.decode(encoding)
E           UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 115: invalid continuation byte
E           Command: chktex "/tmp/tmpv4hcm0gy"
```

Can somebody reproduce?

**Comment by AbdealiJK** [comment] 2016-09-04 06:03
/newI can reproduce this. But for some reason it doesn't fail on circleci. Probably an issue with the locale/stdout encoding being detected.
But, irrespective, this is an upstream bug, as chktex does give a non-unicode output.
Filed it at https://savannah.nongnu.org/bugs/index.php?49000

**Comment by jayvdb** [comment] 2016-10-11 02:18
A more complete analysis is at #889 ; essentially it is chktex 1.7.3-5 , and is now fixed.
And Circle CI precise images dont encounter this because they are 1.7.2.

**Comment by jayvdb** [comment] 2016-10-11 02:19
I'm not sure how big this bug is. It looks quite bad ; maybe these releases should be blacklisted.
Or maybe it is possible to turn off displaying the source on all recent versions, which may help.

**Comment by jayvdb** [comment] 2016-10-11 02:26
Ok, it is easy enough to avoid the source line which appears to be the only problem, and it wasnt being used anyway.
Using `chktex --format='%k %n in %f %l: %m^M^L' ~/tmp/bad.tex` does the trick.

**Comment by jayvdb** [comment] 2016-10-11 08:08
I've posted more info at https://savannah.nongnu.org/bugs/?49000#comment2 , and cc'd the Debian package maintainer in the hope that they push out a new version, ideally as a security update.

**Comment by jayvdb** [comment] 2016-10-11 17:49
btw, the resource I used for `--format` string was https://www.nongnu.org/chktex/ChkTeX.pdf .  I didnt see it documented in the `--help` anywhere.

**Closed** 2016-10-13 13:18 UTC
Labels: type/bug, upstream
