### ISSUE TITLE
Travis CI build fail due to Assertion failure in DartLintBearTest

### ISSUE THREAD

**Issue by kriti21** [coala/coala-bears#2557] opened 2018-06-30 10:39 UTC
Here is a link to two PRs that I am working on and for which travis CI builds are failing for some unknown reason that is unrelated to my changes.

https://travis-ci.org/coala/coala-bears/builds/398495705?utm_source=github_status&utm_medium=notification

https://travis-ci.org/coala/coala-bears/builds/398505168?utm_source=github_status&utm_medium=notification

The only thing that I find common in both of these is:
```
../../../virtualenv/python3.4.6/lib/python3.4/site-packages/coalib/testing/LocalBearTestHelper.py:175: in check_invalidity
    self.assertNotEqual(len(bear_output), 0, msg=msg)
E   AssertionError: 0 == 0 : The local bear 'DartLintBear' yields no result although it should.
```

In my PRs I see  the build failing in `RubySmellBearTest`, `DartLintBearTest`and `StyleLintBearTest` only. However, I am not sure if this failure is due to the bears themselves or the functions used for testing them like `check_invalidity()` which is part of coala/coala repo.

**Comment by kriti21** [comment] 2018-06-30 10:45
@jayvdb @damngamerz @refeed Please see if you can provide some more info related to this issue so that it can be solved asap.

**Comment by jayvdb** [comment] 2018-07-01 11:50
There have been no changes to coala.
Your CI logs show they are using:
`coala-0.12.0.dev20180101025653 coala-utils-0.6.7`

These are CI problems in this repo , usually caused by changes in other repositories.

https://travis-ci.org/coala/coala-bears/jobs/398505169 shows problems with `DartLintBearTest` and `RubySmellBearTest` still exist, but `StyleLintBearTest` magically fixed itself.

**Comment by jayvdb** [comment] 2018-07-01 12:08
The ruby version hasnt changed.

RubySmell is gem `reek` with a new release, which is a common source of failures, and should be easy to fix.  c.f. #2558 created about that one.

So now this issue can be about dart only.

**Comment by jayvdb** [comment] 2018-07-01 18:18
The problem with DartBear also seems to have disappeared, at least it isnt present with recent builds of coala-bears master. https://travis-ci.org/coala/coala-bears/builds/398801319

**Comment by kriti21** [comment] 2018-07-01 18:41
I am not quite sure though. May be I am completely wrong here but I pushed changes in my PR multiple times (my bad) but logs were different and I still think if nothing has been changed, the bear is flaky. Just a FYI, travis.yml downloads an old version of dart sdk

**Comment by jayvdb** [comment] 2018-07-02 00:55
It is definitely concerning that we had those problematic builds, and we dont know why they failed. As it is fetching a versioned zip (and an old version as you've found), it really shouldnt change.
But we cant reproduce it now, so we cant analyse it now, and will need to wait until it reoccurs.
This is why we include as much detail in issues as possible, so we can find them again when a breakage re-occurs

There is also a strange coverage problem occurring in my build of RLintBear.  py34 and py35 jobs didnt execute `create_arguments`, but py36 did.  As that type of failure should have nothing to do with Python version, that type of failure often means the caches of some of the jobs is stale, and the problem will likely hit all jobs once their caches become stale.
https://travis-ci.org/jayvdb/coala-bears/builds/398878069

**Comment by jayvdb** [comment] 2018-07-02 01:14
Ruby fixed in https://github.com/coala/coala-bears/pull/2559 , with build at https://travis-ci.org/coala/coala-bears/builds/398948529 and my fork at https://travis-ci.org/jayvdb/coala-bears/builds/398948420 .  Hopefully those pass, and we can get back to normal coding.

**Comment by jayvdb** [comment] 2018-07-02 02:09
Bugger : https://travis-ci.org/coala/coala-bears/builds/398948529 shows all jobs failing on RLintBear.
I suspect that it means all builds need to start with a fresh cache.
I've deleted all the caches on my Travis fork, and restarted [the py34 job which previously failed](https://travis-ci.org/jayvdb/coala-bears/jobs/398948421) .  If it passes, all that is needed is to delete all the caches on coala/coala Travis project, and rebuild the reek version.

Note we also have a vint error on Windows now. https://ci.appveyor.com/project/coala/coala-bears/build/1.0.9919/job/rf4116akpq7rn5vu

When it rains, it pours.

**Comment by kriti21** [comment] 2018-07-02 02:42
> Note we also have a vint error on Windows now.
Yup opened an issue for that already https://github.com/coala/coala-bears/issues/2556

**Comment by jayvdb** [comment] 2018-07-02 15:52
With patches for the reek and vint problems , and green builds, this can be closed until it reappears.

**Closed by jayvdb** 2018-07-02 15:52 UTC
Labels: area/ci, area/tests
