### ISSUE TITLE
Cacheing says it will run on file, but doesn't

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-bears#787] opened 2016-09-03 17:34 UTC
I was running coala on a JS file, and it worked the first time. but didn't the second time.

```
(py35_coala) [ajk@localhost coala-bears]$ coala -I -b ESLintBear -f a.js -S eslint_config=/home/ajk/Documents/coala/coala-bears/tests/js/test_files/eslintconfig_badplugin.json -L DEBUG
[DEBUG][22:57:48] Platform Linux -- Python 3.5.1, pip 8.1.2, coalib 0.9.0.dev99999999999999
Executing section Default...
[DEBUG][22:57:48] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][22:57:48] Files that will be checked:
/home/ajk/Documents/coala/coala-bears/a.js
[DEBUG][22:57:48] Running bear ESLintBear...
[DEBUG][22:57:48] Running 'eslint --no-ignore --no-color -f=json --stdin --config /home/ajk/Documents/coala/coala-bears/tests/js/test_files/eslintconfig_badplugin.json'
[WARNING][22:57:48] Error while running ESLintBear.
[WARNING][22:57:48] Failed to load plugin invalid_plugin_should_throw_error: Cannot find module 'eslint-plugin-invalid_plugin_should_throw_error'
Error: Failed to load plugin invalid_plugin_should_throw_error: Cannot find module 'eslint-plugin-invalid_plugin_should_throw_error'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/home/ajk/Documents/coala/coala-bears/node_modules/eslint/lib/config/plugins.js:119:26)
    at Array.forEach (native)
    at Object.loadAll (/home/ajk/Documents/coala/coala-bears/node_modules/eslint/lib/config/plugins.js:141:21)
    at Object.load (/home/ajk/Documents/coala/coala-bears/node_modules/eslint/lib/config/config-file.js:504:21)
    at loadConfig (/home/ajk/Documents/coala/coala-bears/node_modules/eslint/lib/config.js:63:33)
    at new Config (/home/ajk/Documents/coala/coala-bears/node_modules/eslint/lib/config.js:226:38)
(py35_coala) [ajk@localhost coala-bears]$ coala -I -b ESLintBear -f a.js -S eslint_config=/home/ajk/Documents/coala/coala-bears/tests/js/test_files/eslintconfig_badplugin.json -L DEBUG
[DEBUG][22:58:34] Platform Linux -- Python 3.5.1, pip 8.1.2, coalib 0.9.0.dev99999999999999
Executing section Default...
[DEBUG][22:58:34] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][22:58:34] Files that will be checked:
/home/ajk/Documents/coala/coala-bears/a.js
(py35_coala) [ajk@localhost coala-bears]$
```

Note that the second time it does not say "Running bear ESLintBear ..."

**Comment by sils1297** [comment] 2016-09-03 17:41
sorry I don't fully get it, in the first run there were no results so caching assumed that nothing's wrong and the second time no files were checked because they're cached as "ok". What exactly is your problem?

**Comment by AbdealiJK** [comment] 2016-09-03 17:45
coala says in the DEBUG:
```
[DEBUG][22:58:34] Files that will be checked:
/home/ajk/Documents/coala/coala-bears/a.js
```
So, should it not have checked that file ?
It says it is going to check it, but no file was actually checked.

**Comment by sils1297** [comment] 2016-09-03 17:48
ah we probably should show a hint like `a.js (cached, will be omitted)` or so but this is more like an unclear thing in the debug messages, not fully sure if its a bug.

**Comment by hypothesist** [comment] 2016-09-03 17:50
@sils1297 shouldn't it reproduce the same error when ran the second time?

**Comment by sils1297** [comment] 2016-09-03 17:51
@hypothesist well ideally but that's not possible until @Uran198 finishes his logging switch to builtin logging, then every bear can get an own logger and we can identify which log messages come from wher

**Comment by jayvdb** [comment] 2017-04-21 09:32
> shouldn't it reproduce the same error when ran the second time?

This was fixed by https://github.com/coala/coala/pull/3722

**Closed by jayvdb** 2017-04-21 09:32 UTC
Labels: status/needs design
