### ISSUE TITLE
KeywordBear should not require setting the language

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#1956] opened 2017-07-27 12:24 UTC
I want to use KeywordBear to do a simple text search, but it's not really cooperating. It needs the language to be set, which is bad for two reasons

- If my language is not understood by coala, I can't use the KeywordBear
- I can't search for the text `FIXME` across all my files, I'd need to have separate sections for Python, JS, HTML, CSS, Markdown, and so on.

**Comment by Makman2** [comment] 2017-07-27 12:39
Yeah this is definitely bad :+1:

**Comment by jayvdb** [comment] 2017-07-27 12:42
We have a bunch of bugs about this already, and PRs which were blocked but can probably be rescued.

**Comment by underyx** [comment] 2018-03-19 14:48
Does anyone remember which coala version introduced this issue? I guess we have to downgrade to be able to use keyword checks at all.

**Comment by Makman2** [comment] 2018-03-20 22:15
No sorry, I guess you have to `git blame` through the `KeywordBear`.

**Comment by jayvdb** [comment] 2018-11-29 13:31
Duplicate of https://github.com/coala/coala-bears/issues/1012

Last good version was 0.8

**Closed by jayvdb** 2018-11-29 13:31 UTC
Labels: importance/high, status/needs design
