### ISSUE TITLE
README.rst : Supported languages should be dynamic

### ISSUE THREAD

**Issue by IpshitaC** [coala/coala-bears#2169] opened 2017-12-15 04:38 UTC
Add HAML to the list of supported languages.
Relevant file can be found [here](https://github.com/coala/coala-bears/blob/master/README.rst#languages-supported)
Relevant commit can be found [here](https://github.com/coala/coala-bears/commit/c86a6d0f4c88521d5701c7d2fc7c1e9d989bb08a)

difficulty/newcomer area/documentation

**Comment by IpshitaC** [comment] 2017-12-15 04:39
@jayvdb could this be used as a GCI task?

**Comment by Makman2** [comment] 2017-12-16 18:58
Let's keep it standalone :+1: @IpshitaC

**Comment by RaiVaibhav** [comment] 2017-12-16 22:03
```
coalaBear
DuplicateFileBear
FilenameBear
InvalidLinkBear
KeywordBear
LicenseCheckBear
LineCountBear
LineLengthBear
MementoBear
SpaceConsistencyBear
URLBear
```
@IpshitaC  Just tried `coala --show-bears --filter-by-language HAML`
But `HAMLLintBear` is not up there.(don't know much about it's working)
Also https://coala.io/#/languages is also needs to be updated as per `HAML`.

**Comment by Makman2** [comment] 2017-12-16 23:22
We recently merged `HAMLBear`, so it will appear once you upgrade to the newest coala-bears ;) @RaiVaibhav

**Comment by sanshay** [comment] 2018-04-21 19:59
@ishanSrt @Makman2 can anyone of you please assign this issue to me.

**Comment by jayvdb** [comment] 2018-04-21 23:33
Hi @sanshay , sorry to unassign you.

This issue keeps occurring whenever we add new bears, and just adding HAML isnt enough.  We have quite a few other languages also supported since it was last updated.

The README should be generated with `moban` so that the list is always up to date.

**Comment by jayvdb** [comment] 2018-11-03 07:11
Duplicate of https://github.com/coala/coala-bears/issues/1609

**Closed by jayvdb** 2018-11-03 07:11 UTC
Labels: area/documentation, difficulty/medium, importance/medium
