### ISSUE TITLE
.coafile: Ignore all orig files in the coala-bears dir

### ISSUE THREAD

**Issue by nemaniarjun** [coala/coala-bears#2510] opened 2018-05-27 00:56 UTC
Right now coala does not ignore .orig files in the .ci folder
It should as they are just backups and not meant to be commited.

difficulty/newcomer

**Comment by jayvdb** [comment] 2018-05-27 04:50
why not ignore .orig in all folders?

Also, can our .coafile specify that backups should not be created?
Would that be a good idea?

**Comment by utkarsh2102** [comment] 2018-05-29 15:58
Can I take this @nemaniarjun, @jayvdb?

**Comment by Makman2** [comment] 2018-06-05 15:08
I would like to have an option to suppress generation of backup files. Not needed in CI for example^^

**Comment by Makman2** [comment] 2018-06-05 15:10
I just remember that backup files usually cluttered my git workspace. If you use git, that's usually enough as "backup", as you can always revert changes.

**Comment by nemaniarjun** [comment] 2018-06-05 15:45
@utkarsh2102 sure, just wait till someone assigns it to you, or ask on gitter. 

@Makman2 This issue is not about generation of backup files, but about coala accidentally being ran on the .orig files, which just results in oldfile.orig.orig.orig files :tongue:

**Comment by Makman2** [comment] 2018-06-10 20:18
Referring to :point_up: https://github.com/coala/coala-bears/issues/2510#issuecomment-392305157

**Comment by jayvdb** [comment] 2018-06-11 00:55
IMO this should be done as part of (or after) https://gitlab.com/coala/mobans/issues/1 .
Otherwise we have lots of differences to all of the repos, and it is hard to remember all the variations.

**Comment by MacBox7** [comment] 2018-06-11 05:16
Duplicate of https://github.com/coala/coala-bears/issues/2389

**Closed** 2018-07-06 10:57 UTC
Labels: status/duplicate
