### ISSUE TITLE
Bear Proposal: HTTPSBear

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala-bears#2166] opened 2017-12-14 12:58 UTC
Nowadays, using `https://` is pretty mandatory and encouraged. I propose a bear which will enforce this rule and preventing the usage of `http://`.

**Comment by Makman2** [comment] 2017-12-14 23:00
Duplicate of https://github.com/coala/coala-bears/issues/1900 :)

**Closed by Makman2** 2017-12-14 23:00 UTC
Labels: bear proposal
