### ISSUE TITLE
Travis CI logs fail due to failing pep8 tests.

### ISSUE THREAD

**Issue by sladyn98** [coala/coala-bears#2847] opened 2019-01-31 17:52 UTC
https://travis-ci.org/frextrite/coala-bears/jobs/486981236#L4739.
Taking a look at the obove travis CI logs we can see that Pycodestyle bear complains with errors.
[`  38] ········by·GitHub·in·a·refs/pull/(\d+)/merge·git·remote·reference.
**** PycodestyleBear (W605) [Section: all.autopep8 | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\d'`

`[ 248] ····statement,·i.e.·within·the·operators·\*,·/,·%·and·their·associated·compound
**** PycodestyleBear (W605) [Section: all.autopep8 | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\*'`

`[WARNING][15:09:42] PycodestyleBear (W605): This result has no patch attached.
bears/c_languages/codeclone_detection/ClangCountingConditions.py`

**Comment by jayvdb** [comment] 2019-01-31 22:06
Duplicate of https://github.com/coala/coala-bears/issues/2760

**Closed by jayvdb** 2019-01-31 22:06 UTC
Labels: type/bug
