### ISSUE TITLE
Fix spelling mistake 

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala-bears#2629] opened 2018-07-21 08:22 UTC
`parseable` ---> `parsable`
https://github.com/coala/coala-bears/blob/master/bears/python/requirements/PySafetyBear.py#L97

difficulty/newcommer

**Comment by prankshaw** [comment] 2018-07-21 19:00
I will like to review this issue. Please tell me how can I achieve that

**Comment by jayvdb** [comment] 2018-07-23 00:17
Duplicate of https://github.com/coala/coala-bears/issues/2299

**Closed by jayvdb** 2018-07-23 00:17 UTC
Labels: difficulty/newcomer, type/spelling
