### ISSUE TITLE
PEP8Bear doesn't respect ignoring comment

### ISSUE THREAD

**Issue by Joozty** [coala/coala-bears#2793] opened 2018-11-27 08:23 UTC
Maybe I am doing something wrong but ignoring comment in my file doesn't work.

Here is a very example of my `coala_test.py`:

```python3
import os

# Start ignoring PEP8Bear
import sys
sys.path.append(".")
import json

# Stop ignoring
```

When I run this command  `coala --bears=PEP8Bear -f coala_test.py` it wants me  to apply this patch:

```python3
import json
import os

# Start ignoring PEP8Bear
import sys
sys.path.append(".")
import json

# Stop ignoring
```

Which doesn't make sense. 

I am running `python3.6.6`, coala `0.11.0`, coala-bears `0.11.1`

Thanks for help.

**Comment by li-boxuan** [comment] 2018-11-27 13:57
Possibly a duplicate of https://github.com/coala/coala/issues/3365

I am able to reproduce using coala `0.11.0`. This issue seems to have been solved some time ago because I cannot reproduce using coala master.

Could you try using the latest coala `master`? @Joozty

**Comment by Joozty** [comment] 2018-11-28 08:00
@li-boxuan I can confirm the issue is not on master. Unfortunately, I had to use a `master` version of `coala-bears` too otherwise I had version conflict error. 

Just for the record, my `requirements.txt` looks like this now:
``
git+https://github.com/coala/coala.git@master
git+https://github.com/coala/coala-bears.git@master
```

Do you know when will be released new version of `coala`?

**Comment by li-boxuan** [comment] 2018-11-28 09:52
@Joozty Sorry there is no concrete plan for a release in the near future. I would suggest using `master` version.

**Closed** 2018-11-28 09:52 UTC
Labels: type/bug

**Comment by Joozty** [comment] 2018-12-10 13:35
@li-boxuan 

It doesn't work for this input (even I use master version):
```
import os

# Start ignoring PEP8Bear
import sys
sys.path.append(".")
from json import scanner

# Stop ignoring
```

**Comment by li-boxuan** [comment] 2018-12-13 11:49
@Joozty It works for me. Did you try using a virtual environment?

Are you saying it works for
```python
import os

# Start ignoring PEP8Bear
import sys
sys.path.append(".")
import json

# Stop ignoring
```
but not
```python
import os

# Start ignoring PEP8Bear
import sys
sys.path.append(".")
from json import scanner

# Stop ignoring
```
?
