### ISSUE TITLE
YAMLLintBear interprets indentation as whitespace

### ISSUE THREAD

**Issue by hemangsk** [coala/coala-bears#1252] opened 2017-01-03 20:51 UTC
YAML files such as configuration for travis have nested settings requiring indentation. YAMLLintBear currently doesn't know about any such scenarios. 

Steps to reproduce
1. File abc.yml
```
language: ruby
rvm:
- 2.2.5

install: gem install jekyll

script: jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
```

2. coala --bears YAMLLintBear --files abc.yml
```
abc.yml
|  10| ••global:
|    | [MAJOR] YAMLLintBear:
|    | wrong indentation: expected 0 but found 2 (indentation)
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit): 
```

But as we can see `global` is a setting for `env`, and it should be indented. 

Additonal Info
yamllint version 1.6.0

**Comment by jayvdb** [comment] 2017-01-04 09:16
What version of yamllint do you have installed?

```
$ yamllint --version
yamllint 1.5.0
$ cat yamllint.conf.json 
{
   "extends": "default",
   "rules": {
     "document-start": {
       "present": false
     }
  }
}
$ yamllint abc.yml 
abc.yml
  1:1       warning  missing document start "---"  (document-start)
  11:42     warning  too few spaces before comment  (comments)
$ yamllint --config-file yamllint.conf.json abc.yml 
abc.yml
  11:42     warning  too few spaces before comment  (comments)
$ coala --ci -I --bears YAMLLintBear --files abc.yml --verbose
Executing section Default...
[DEBUG][16:10:50] Running bear YAMLLintBear...
[DEBUG][16:10:50] Running 'yamllint -f parsable /home/jayvdb/tmp/abc.yml --config-file=/tmp/tmpcl8_msnj'
$
```
(which is also weird because where did the "too few spaces before comment" warning disappear to?)

**Comment by hemangsk** [comment] 2017-01-04 09:19
I mistakenly added the wrong version of file, its supposed to be without any comments,
 sorry I'll just correct it in a sec!

**Comment by hemangsk** [comment] 2017-01-04 09:23
Done 👍

**Comment by hemangsk** [comment] 2017-01-04 18:48
yammlint version is 1.6.0

**Comment by hemangsk** [comment] 2017-01-04 18:53
```
$ cat abc.yml
language: ruby
rvm:
- 2.2.5

install: gem install jekyll

script: jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false


$ yamllint --version
yamllint 1.6.0


$ coala --bears YAMLLintBear --files abc.yml
[WARNING][00:22:06] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
Executing section Default...

abc.yml
|  10| ••global:
|    | [MAJOR] YAMLLintBear:
|    | wrong indentation: expected 0 but found 2 (indentation)
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit): 
```

**Comment by damngamerz** [comment] 2017-02-20 21:14
Im trying to solve this issue.I have found 1 config which clears this error 
`yamllint -d "{extends: default, rules: {indentation: {indent-sequences: whatever}}}" abc.yml`
And we have `yamllint_config` for using configuration files with YAMLLintBear.
with `indent-sequences: consistent` which is a default setting,hence the problem is with this particular setting.
Any thoughts about how to fix this?Or I have to create issue in `yamllint` repo?

**Comment by Makman2** [comment] 2017-02-20 21:55
Can you confirm that this can be solved by upgrading `yamllint`? @damngamerz

**Comment by damngamerz** [comment] 2017-02-22 15:10
@Makman2 The latest version of yamllint is 1.6 The bug still persists!! Tested on my local environment.
The only solution which i can think of is to particularly use this setting `coala --bears=YAMLLintBear -S yamllint_config=.yamllint --files=abc.yml 
`
where `.yamllint` will have
```
---

extends: default

rules:
  indentation:
    indent-sequences: whatever
```
Or else need to create an issue in yamllint repo about this bug.

**Comment by Makman2** [comment] 2017-02-24 20:53
okay I've read a bit about this setting:

> indent-sequences defines whether block sequences should be indented or not (when in a mapping, this indentation is not mandatory – some people perceive the - as part of the indentation). Possible values: true, false, whatever and consistent. consistent requires either all block sequences to be indented, or none to be. whatever means either indenting or not indenting individual block sequences is OK.

So the problem is that YAMLLint does mix up nested blocks with the indentation style with `-`. So in our configuration, the `- xxx` items need all indentation to pass the check. I'm not sure whether YAMLLint should distinct between normal nested items and `-` lists. @damngamerz but I think we should file an issue for them and discuss the behaviour :)

**Comment by damngamerz** [comment] 2017-02-25 19:13
@Makman2 @hemangsk 
The file `abc.yml` should be written in this way.
YAMLLintBear passes this file.
```
language: ruby
rvm:
  - 2.2.5

install: gem install jekyll

script: jekyll build

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
```
But theres some serious bug with 
indentation setting
`indent-sequences:consistent` which is a `default` setting in yamllint.
In original `abc.yml`
it should have thrown error at line 3 and 11 telling us about indentation required(something like that).i.e. at
```
rvm:
- 2.2.5
```
and
```
global:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
```
but it throws that above error.I have reported this bug with the maintainers of yamllint.
Hope this issue can be closed now.

**Comment by Makman2** [comment] 2017-02-25 21:32
@damngamerz could you provide the link here to your filed issue?

**Comment by damngamerz** [comment] 2017-02-25 21:48
@Makman2 here https://github.com/adrienverge/yamllint/issues/39

**Comment by Makman2** [comment] 2017-02-27 19:23
So now it should error correctly on the first `- xxx` element, am I right? @damngamerz

**Comment by Makman2** [comment] 2017-02-27 19:24
means our travis file is not written in good style ;)

**Comment by damngamerz** [comment] 2017-02-27 19:28
yup it shows error now at our first `- xxx` i have checked it locally.It worth the update `1.6.1` @Makman2 :+1: 
Travis is failing due to https://github.com/coala/coala-bears/issues/1084 
So do i have to wait for travis-ci to be fixed before the PR gets merged?(Need all green ticks i guess).

**Comment by Makman2** [comment] 2017-02-27 20:20
If this is the cause, then yes :+1:

**Closed** 2017-03-06 07:00 UTC
Labels: type/bug
