### ISSUE TITLE
KeywordBear in 0.11 RC doesn't allow unsetting 'keywords' setting anymore

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#1689] opened 2017-04-29 18:03 UTC
Try this `.coafile`:

```
[keywords]
files = .coafile
language = coafile
bears = KeywordBear
regex_keywords = some_(useful|weird)_regex_pattern
# next line unsets the default 'FIXME' value
keywords =
```

Instead of yielding 0 results as expected, it will yield 907; one for each occurrence of the empty string.

Pinging @Mixih since it's a release blocker I assume.

**Comment by Mixih** [comment] 2017-04-29 18:28
Extremely urgent, @NiklasMM wanna look at this as you did the release code stuff?

**Comment by underyx** [comment] 2017-04-29 18:28
Also, once this is fixed, please check KeywordBear regex and non-regex performance, it seemed a bit off but it might be cause of this bug, and it was difficult to test it while this issue is still open.

**Comment by Mixih** [comment] 2017-04-29 19:14
not a regression as it doesn't work with 0.10 and was obviously broken in 0.9. Still extremely urgent

**Comment by Mixih** [comment] 2017-04-29 20:42
Triaged. This is an old KeywordBear problem where the empty `keyword` setting is not handled. Should be fixable by adding a case if the setting is empty.

**Comment by meetmangukiya** [comment] 2017-04-29 22:17
Copy, paste from commit message:

If a setting is used in the coafile and nothing is assigned, then the value of that key is an empty string ''. Now, since `keywords` is a `list`, `list('')` returns an empty list: `[]` which leads to construction of regex `r'()'` which matches every character, and hence produces false results.

**Comment by Makman2** [comment] 2017-04-29 23:11
Shouldn't we patch the parser instead to consider empty strings to be an empty list?

**Comment by meetmangukiya** [comment] 2017-04-30 05:23
@Makman2 here an empty list is created, so, no. ;)

**Comment by Makman2** [comment] 2017-04-30 12:29
ah nvm have misunderstood your comment above :+1:

**Comment by jayvdb** [comment] 2017-05-02 10:38
Note , the bug fixed in #1690, and backported in #1695 , also occurred in 0.10, and it appears to have also occurred in 0.9 from my limited testing.

@underyx , if you are experiencing a regression in 0.11 RC, which version did this work correctly?

This is tightly related to https://github.com/coala/coala/issues/4116 (unsetting default settings).

**Comment by underyx** [comment] 2017-05-02 10:48
@jayvdb found the issue in `0.11.0.rc1`. Our last known working version is with `0.9.1` (we're using the 0.9 Docker image.)

**Comment by underyx** [comment] 2017-05-02 14:11
Oh nooo, sorry, @jayvdb, I just realized that repo uses the `0.8` image, so last known working version is actually `0.8.1`.

**Comment by jayvdb** [comment] 2017-05-02 14:39
Ah, that makes much more sense, as I can reproduce this bug on 0.9.
Now trying 0.8...

**Comment by jayvdb** [comment] 2017-05-02 14:48
yup; confirmed. the regression happened at bfd61fb, and the fix applied in above PRs is correct for that regression.

**Comment by Mixih** [comment] 2017-05-02 15:21
closing issue as discussion has been resolved.

**Closed by Mixih** 2017-05-02 15:21 UTC
Labels: area/usability, importance/critical, needs backport, type/bug
