### ISSUE TITLE
CSSAutoPrefixBear: Pin autoprefixer as 8.0.0 is breaking the tests

### ISSUE THREAD

**Issue by nvzard** [coala/coala-bears#2318] opened 2018-03-09 05:55 UTC

**Comment by jayvdb** [comment] 2018-03-09 06:31
I believe the problem is fixed in 8.1.0

**Comment by jayvdb** [comment] 2018-03-09 06:31
Dup of https://github.com/coala/coala-bears/issues/2315

**Closed by jayvdb** 2018-03-09 06:31 UTC
Labels: type/bug

**Comment by nvzard** [comment] 2018-03-09 15:16
I opened the issue in respect of my commit to just pin the autoprefixer to fix masterbranch, https://github.com/coala/coala-bears/issues/2315 is to adapt the tests as per the latest version.
No issues if this is not correct

**Comment by jayvdb** [comment] 2018-03-09 15:30
#2315 is mostly about the breakage; analysis hasnt been done yet, so no need for lots of different issues about the same thing.
