### ISSUE TITLE
JavaPMDBear wrong execution command on Windows

### ISSUE THREAD

**Issue by frextrite** [coala/coala-bears#2933] opened 2019-07-08 11:44 UTC
```
[DEBUG][17:09:36] Running 'bash C:\Users\amolg\pmd-bin-6.16.0\bin\pmd.BAT pmd -R java-basic,java-braces,java-clone,java-codesize,java-imports,java-naming,java-unnecessary,java-unusedcode -d c:\users\amolg\documents\github\coala-jetbrains\src\main\java\io\coala\jetbrains\utils\CodeAnalysisIssue.java'
WARNING:root:JavaPMDBear: Discarded stderr: /bin/bash: C:Usersamolgpmd-bin-6.16.0binpmd.BAT: No such file or directory

WARNING:root:JavaPMDBear: Exit code 127
```

`JavaPMDBear` is generating 
```
bash C:\Users\amolg\pmd-bin-6.16.0\bin\pmd.BAT pmd -R java-basic,java-braces,java-clone,java-codesize,java-imports,java-naming,java-unnecessary,java-unusedcode -d c:\users\amolg\documents\github\coala-jetbrains\src\main\java\io\coala\jetbrains\utils\CodeAnalysisIssue.java
```
command on windows.

The actual generated (and working) command should be (minus the bash prefix and pmd argument)
```
C:\Users\amolg\pmd-bin-6.16.0\bin\pmd.BAT -R java-basic,java-braces,java-clone,java-codesize,java-imports,java-naming,java-unnecessary,java-unusedcode -d c:\users\amolg\documents\github\coala-jetbrains\src\main\java\io\coala\jetbrains\utils\CodeAnalysisIssue.java
```

Windows 10 build 18362.207

**Comment by jayvdb** [comment] 2019-08-03 14:36
Duplicate of https://github.com/coala/coala-bears/issues/2908

**Closed by jayvdb** 2019-08-03 14:36 UTC
