### ISSUE TITLE
Error in execute_bear doesnt show error

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1035] opened 2016-11-21 16:51 UTC
e.g. for https://github.com/coala/coala-bears/issues/1034, this is the `py.test` output, which isnt very helpful:

```python
        try:
            bear_output_generator = bear.execute(*args, **kwargs)
            assert bear_output_generator is not None, \
                "Bear returned None on execution\n"
            yield bear_output_generator
        except Exception as err:
            msg = []
            while not bear.message_queue.empty():
                msg.append(bear.message_queue.get().message)
>           raise AssertionError(str(err) + " \n" + "\n".join(msg))
E           AssertionError: 0 == 0 : The local bear 'CheckstyleBear' yields no result although it should. 
E           Running bear CheckstyleBear...
E           Running 'java -jar /home/ubuntu/.local/share/coala-bears/CheckstyleBear/checkstyle.jar -c /home/ubuntu/.local/share/coala-bears/CheckstyleBear/google.xml /home/ubuntu/coala-bears/tests/java/test_files/CheckstyleGood.java'
E           Running bear CheckstyleBear...
E           Running 'java -jar /home/ubuntu/.local/share/coala-bears/CheckstyleBear/checkstyle.jar -c /home/ubuntu/.local/share/coala-bears/CheckstyleBear/google.xml /home/ubuntu/coala-bears/tests/java/test_files/CheckstyleBad.java'

tests/LocalBearTestHelper.py:34: AssertionError
```

**Comment by yash-nisar** [comment] 2017-03-26 08:20
Duplicate of https://github.com/coala/coala-bears/issues/455

**Comment by yash-nisar** [comment] 2017-03-26 08:31
Maybe we close the earlier one :)

**Closed** 2017-03-26 13:49 UTC
Labels: status/duplicate
