### ISSUE TITLE
Bear Proposal: GitlintBear

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala-bears#1553] opened 2017-03-28 07:25 UTC
[Gitlint](https://pypi.python.org/pypi/gitlint) is a tool similar to our native GitCommitBear.

Since it operates on project scope it could be a nice reference implementation of [global linter bears](https://github.com/coala/coala/pull/3652).

Documentation can be found [here](https://jorisroovers.github.io/gitlint/)

**Comment by sils** [comment] 2017-03-29 18:11
duplicate of https://github.com/coala/coala-bears/issues/295#issuecomment-290096625 we should continue the discussion there IMO

**Closed by sils** 2017-03-29 18:11 UTC
Labels: area/lintbears, bear proposal, difficulty/low
