### ISSUE TITLE
.gitignore: Add .pytest_cache/

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2395] opened 2018-03-31 20:54 UTC
difficulty/newcomer

**Comment by sangamcse** [comment] 2018-03-31 20:55
Duplicate of https://github.com/coala/coala-bears/issues/2326

**Comment by MacBox7** [comment] 2018-03-31 20:57
Ah! My bad. Nice catch 😉

**Closed** 2018-03-31 20:57 UTC
Labels: area/ci, difficulty/newcomer
