### ISSUE TITLE
Move to composer for php dependencies

### ISSUE THREAD

**Issue by SanketDG** [coala/coala-bears#2187] opened 2017-12-20 12:07 UTC
For php linting tools, we are better off using a composer setup than using distro packages https://github.com/coala/coala-bears/blob/master/.ci/deps.apt.sh#L28 or manual setup https://github.com/coala/coala-bears/blob/master/.ci/deps.sh#L52

**Comment by SanketDG** [comment] 2017-12-20 12:17
Related to https://github.com/coala/coala-bears/issues/293 which deals with adding composer, but this is for adding the existing tools that are supported by composer

**Comment by jayvdb** [comment] 2017-12-21 02:06
> we are better off using a composer setup than using distro packages /.ci/deps.apt.sh@master#L28 

why?  apt is faster.

> or manual setup /.ci/deps.sh@master#L52

again, why?

**Comment by jayvdb** [comment] 2017-12-21 02:07
The first step is adding ComposerRequirements to the relevant bears.

**Comment by SanketDG** [comment] 2017-12-21 05:54
> > we are better off using a composer setup than using distro packages /.ci/deps.apt.sh@master#L28
> why? apt is faster.

one good reason would be the sync time of a version release, not to mention 14.04's apt is a little old now :)


> or manual setup /.ci/deps.sh@master#L52
> again, why?

manually setting up dependencies when a package manager is readily available, that's odd right?

we use other major package managers, why not use one for php?

**Comment by sangamcse** [comment] 2018-03-10 16:01
@jayvdb, Is there other issue open to add `ComposerRequirements` to it's respective bears or it will be added from this issue only? 
> The first step is adding ComposerRequirements to the relevant bears.

**Comment by jayvdb** [comment] 2018-04-18 14:14
Duplicate of https://github.com/coala/coala-bears/issues/293

**Closed by jayvdb** 2018-04-18 14:14 UTC
Labels: area/lintbears, difficulty/medium, status/blocked
